apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: in-stock-notifier
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: service
              image: ghcr.io/philliphemleb/in-stock-notifier/in-stock-notifier:latest
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /tmp
                  name: tmp-volume
              env: []
              envFrom: []
          restartPolicy: OnFailure
          imagePullSecrets: []
          volumes:
            - name: tmp-volume
              emptyDir: { }
